### ISSUE TITLE
Multiple Cameras

### ISSUE THREAD

**Issue by jon-lind-sn** [ServiceNowNextExperience/photobooth#9]
Need to support 3rd party web cam.

**Comment by phifogg** [comment]
thta's probably why i do not see an image.... my webcam turns on but no image in the browser. No Snap action :/

**Comment by jon-lind-sn** [comment]
@phifogg have you used the toggle below the canvas to turn the camera on?

**Comment by phifogg** [comment]
Ah... the trick was that I needed to create a photobooth record with name 'MyPB'. That is missing in the docs (or I didn't see it).

**Comment by jon-lind-sn** [comment]
Have added multi-camera support, including the ability to save the camera selection to the Photobooth Instance record.
